name = "image-hosting"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Cloudinary 配置 (https://cloudinary.com/)
CLOUDINARY_CLOUD_NAME = ""
CLOUDINARY_API_KEY = ""
CLOUDINARY_API_SECRET = ""

# ImgBB 配置 (https://api.imgbb.com/)
IMGBB_API_KEY = ""
